#!/usr/bin/env bash
#
# Return the major and minor version numbers of the Ruby interpreter. The
# patchlevel is omitted. When a Ruby interpreter is missing, nothing is echoed.
# Always exit with 0.

if [ ! -x "$(command -v ruby)" ]; then
  # No Ruby interpreter found
  exit
fi

ruby -e "puts RUBY_VERSION.split('.')[0..1].join('.')" || true
